export const columns = [
    {
        field:"id",
        headerName:"ID",
        width:33,

    },
    {
        field:"registerId",
        headerName:"Register ID",
        flex:1,
    },
    {
        field:"name",
        headerName:"Name",
        flex:1,
    },
    {
        field:"age",
        headerName:"Age",
        width:33,
    },
    {
        field:"phone",
        headerName:"Phone Number",
        flex:1,
    },
    {
        field:"address",
        headerName:"Address",
        flex:1,
    },
    {
        field:"city",
        headerName:"City",
    },
    {
        field:"zipCode",
        headerName:"zip Code",

    }
]
export const rows = [
    {
        id:1,
        registerId:"#123456",
        name:"John Doe",
        age:25,
        phone:"123-456-7890",
        address:"123 Main St, Cityville",
        city:"Cityville",
        zipCode:"12345",
    },
    {
        id:2,
        registerId:"#654321",
        name:"Jane Smith",
        age:30,
        phone:"987-654-3210",
        address:"456 Elm St, Townsville",
        city:"Townsville",
        zipCode:"54321",
    },
    {
        id:3,
        registerId:"#789012",
        name:"Alice Johnson",
        age:28,
        phone:"555-123-4567",
        address:"789 Oak St, Villagetown",
        city:"Villagetown",
        zipCode:"67890",
    },
    {
        id:4,
        registerId:"#345678",
        name:"Bob Brown",
        age:35,
        phone:"444-987-6543",
        address:"321 Pine St, Hamletburg",
        city:"Hamletburg",
        zipCode:"09876",
    },
    {
        id:5,
        registerId:"#901234",
        name:"Charlie Green",
        age:40,
        phone:"222-555-1212",
        address:"654 Cedar St, Boroughville",
        city:"Boroughville",
        zipCode:"13579",
    },
    {
        id:6,
        registerId:"#567890",
        name:"Diana White",
        age:32,
        phone:"111-222-3333",
        address:"987 Birch St, Districttown",
        city:"Districttown",
        zipCode:"24680",
    },
    {
        id:7,
        registerId:"#234567",
        name:"Ethan Black",
        age:27,
        phone:"333-444-5555",
        address:"159 Spruce St, Regionville",
        city:"Regionville",
        zipCode:"86420",
    },
    {
        id:8,
        registerId:"#890123",
        name:"Fiona Blue",
        age:29,
        phone:"666-777-8888",
        address:"753 Willow St, Sectorcity",
        city:"Sectorcity",
        zipCode:"97531",
    },
    {
        id:9,
        registerId:"#456789",
        name:"George Yellow",
        age:31,
        phone:"999-888-7777",
        address:"258 Maple St, Areaopolis",
        city:"Areaopolis",
        zipCode:"86420",
    }
]